# Generated by Django 6.0.3 on 2026-04-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(blank=True, max_length=15, null=True)),
                ("crystal", models.IntegerField(default=0)),
                ("crystal_free", models.IntegerField(default=0)),
                ("friend_coin", models.IntegerField(default=0)),
                ("tutorial_progress", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                ("token_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expired_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "tokens",
            },
        ),
    ]
